version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis_prova_quarta
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_prova_quarta
    ports:
      - "5672:5672" # Porta para AMQP (conexão das APIs)
      - "15672:15672" # Porta para a interface de gerenciamento web
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      # Você pode definir usuários e senhas aqui se desejar, 
      # mas para este projeto, o padrão guest/guest é suficiente.
      # RABBITMQ_DEFAULT_USER: user
      # RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /

volumes:
  redis_data:
  rabbitmq_data:
